
name: harcapp_web
description: HarcApp Web (Daniel Iwanicki).

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'https://harcapp.web.app' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.20+20

environment:
  sdk: ^3.8.1

dependencies:

  animated_reorderable_list: ^1.3.0
  clipboard: ^2.0.2
  dio: ^5.8.0+1
  draggable_scrollbar: ^0.1.0
  duration_picker: ^1.2.0
  file_picker: ^10.3.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  go_router: ^17.0.0
  google_fonts: ^6.2.1
  flutter_quill: ^11.5.0
  html: ^0.15.5
  http: ^1.3.0
  idb_shim: ^2.6.5+1
  image: ^4.5.2
  image_picker_web: ^4.0.0
  implicitly_animated_reorderable_list_2: ^0.6.0
  localstorage: ^6.0.0
  logger: ^2.5.0
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  pretty_json: ^2.0.0
  yaml: ^3.1.2
  provider: ^6.1.2
  semaphore_plus: ^0.3.1
  shared_preferences: ^2.5.1
  smooth_scroll_multiplatform: ^1.0.8
  url_strategy: ^0.3.0
  web: 1.1.1
  worker_manager: ^7.2.2
  youtube_player_flutter: ^9.1.1

  harcapp_core:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/screenshots/

  fonts:
    - family: Gentium
      fonts:
        - asset: fonts/GentiumBasic-Regular.ttf
          weight: 300
        - asset: fonts/GentiumBasic-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/GentiumBasic-Bold.ttf
          weight: 700
        - asset: fonts/GentiumBasic-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-B.ttf
          weight: 900
        - asset: fonts/Ubuntu-BI.ttf
          weight: 900
          style: italic
        - asset: fonts/Ubuntu-M.ttf
          weight: 700
        - asset: fonts/Ubuntu-MI.ttf
          weight: 700
          style: italic
        - asset: fonts/Ubuntu-R.ttf
          weight: 500
        - asset: fonts/Ubuntu-RI.ttf
          weight: 500
          style: italic
        - asset: fonts/Ubuntu-L.ttf
          weight: 300
        - asset: fonts/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: fonts/Ubuntu-Th.ttf
          weight: 100