name: harcapp_web
description: HarcAppka Web (Daniel Iwanicki).

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+8

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

  clipboard: ^0.1.3
  draggable_scrollbar: ^0.1.0
  dropdown_button2: ^2.0.0
  file_picker_cross: ^4.4.2
  flutter_mailer: ^2.0.0
  http: ^0.13.4
  image: ^4.0.5
  image_picker_web: ^3.0.0+1
  image_picker: ^0.8.1+1
  implicitly_animated_reorderable_list_2: 0.5.0
  package_info_plus: ^1.0.6
  path_provider: ^2.0.2
  pretty_json: ^2.0.0
  provider: ^6.0.0
  worker_manager: ^5.0.3

  harcapp_core:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core

  harcapp_core_tags:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core_tags

  harcapp_core_song:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core_song

  harcapp_core_song_widget:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core_song_widget

  harcapp_core_own_song:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core_own_song

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/songs/

  fonts:
    - family: Gentium
      fonts:
        - asset: fonts/GentiumBasic-Regular.ttf
          weight: 300
        - asset: fonts/GentiumBasic-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/GentiumBasic-Bold.ttf
          weight: 700
        - asset: fonts/GentiumBasic-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-B.ttf
          weight: 900
        - asset: fonts/Ubuntu-BI.ttf
          weight: 900
          style: italic
        - asset: fonts/Ubuntu-M.ttf
          weight: 700
        - asset: fonts/Ubuntu-MI.ttf
          weight: 700
          style: italic
        - asset: fonts/Ubuntu-R.ttf
          weight: 500
        - asset: fonts/Ubuntu-RI.ttf
          weight: 500
          style: italic
        - asset: fonts/Ubuntu-L.ttf
          weight: 300
        - asset: fonts/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: fonts/Ubuntu-Th.ttf
          weight: 100